<a href="https://colab.research.google.com/github/badstyle-goodstyle/data_engineering/blob/data_engine/data_engine_practice1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Предисловие

Выполнил: Яковцев Дмитрий

Решите задания без использования циклов средствами NumPy (каждый
пункт решается в 1-2 строчки):

# Задача №1

## Создайте вектор с элементами от 12 до 42.

In [3]:
one = np.array(range(12,43))
print(one)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42]


# Задача №2

## Создайте вектор из нулей длины 12, но его пятый элемент должен быть равен 1.

In [7]:
two = np.zeros(12, int)
two[4] = 1
print(two)

[0 0 0 0 1 0 0 0 0 0 0 0]


# Задача №3

## Создайте матрицу (3, 3), заполненную от 0 до 8.

In [8]:
three = np.array(range(9)).reshape((3,3))
print(three)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Задача №4

## Найдите все положительные числа в np.array([1,2,0,0,4,0]).

In [10]:
four = np.array([1, 2, 0, 0, 4, 0])
print(four[four > 0])

[1 2 4]


# Задача №5

## Умножьте матрицу размерности (5, 3) на (3, 2).

In [13]:
a = np.floor(5 * np.random.random((5, 3)))
b = np.floor(3 * np.random.random((3, 2)))
print("A:\n ", a, "\nB:\n ", b)
five = a.dot(b)
print("A * B:\n ", five)

A:
  [[2. 3. 0.]
 [4. 3. 1.]
 [0. 4. 0.]
 [2. 0. 2.]
 [1. 2. 2.]] 
B:
  [[1. 1.]
 [0. 0.]
 [2. 2.]]
A * B:
  [[2. 2.]
 [6. 6.]
 [0. 0.]
 [6. 6.]
 [5. 5.]]


# Задача №6

## Создайте матрицу (10, 10) так, чтобы на границе были 0, а внутри 1.

In [24]:
dummy_zero_hor = np.zeros((1, 10), dtype=int)
six = np.ones((10, 10), dtype=int)
six[0] = six[9] = dummy_zero_hor
six[np.arange(10), 0] = 0
six[np.arange(10), 9] = 0
print(six)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 1 1 1 1 1 1 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]]


# Задача №7

## Создайте рандомный вектор и отсортируйте его.

In [31]:
dummy_vector = np.random.random_sample(5)
print(dummy_vector)
seven = np.sort(dummy_vector)
print(seven)

[0.73744215 0.70433209 0.23556935 0.34447499 0.16363657]
[0.16363657 0.23556935 0.34447499 0.70433209 0.73744215]
